name: microsoft_graph
description: A Dart library for the Microsoft Graph.
version: 0.0.13
homepage: https://github.com/dmytro-glynskyi/microsoft-graph
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_value: ^6.3.2
  built_collection: ^4.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2
  microsoft_graph_http: ^0.0.13
